version: '3.6'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
  create_queues:
    build: .
    command: python create_queue.py A B
    depends_on:
      - localstack
  start_chatting:
    build: .
    command: python init_request.py B 1
    depends_on:
      - create_queues
  run_a:
    build: .
    command: python ping_pong.py A B
    depends_on:
      - start_chatting
  run_b:
    build: .
    command: python ping_pong.py B A
    depends_on:
      - start_chatting
